'use client'; // precisa estar no topo para usar hooks

import { useEffect } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Museu Autobiográfico e Território Leste",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    if (window.location.hostname === "museuautobiografico.vercel.app") {
      window.location.href = "https://museuautobiografico.org";
    }
  }, []);

  return (
    <html lang="pt">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
